package com.example.library_management.model;

public enum Genre {
    FANTASY,SCIENCE_FICTION,MYSTERY,
    THRILLER,HORROR,ROMANCE,HISTORICAL_FICTION,
    LITERARY_FICTION,ADVENTURE,DYSTOPIAN,
    COMING_OF_AGE,MAGICAL_REALISM,BIOGRAPHY,
    AUTOBIOGRAPHY,MEMOIR,SELF_HELP,HISTORY,
    TRUE_CRIME,SCIENCE,NATURE,TRAVEL,PHILOSOPHY,POLITICS,ESSAYS
}
